[project]
name = "django-shop"
version = "0.1.0"
description = "پروژه فروشگاه آنلاین با استفاده از جنگو"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.7",
    "django-debug-toolbar>=7.0.0",
    "django-environ>=0.14.0",
    "gunicorn>=26.0.0",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
]
